"""empty message

Revision ID: b8915dc84771
Revises: a44d575675f0
Create Date: 2020-02-29 18:58:25.464626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8915dc84771'
down_revision = 'a44d575675f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('health', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('max_health', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_health')
    op.drop_column('user', 'health')
    # ### end Alembic commands ###
